// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheBoxApp.Data.Context;

#nullable disable

namespace TheBoxApp.Data.Migrations
{
    [DbContext(typeof(MachineDataContext))]
    [Migration("20231221095131_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("TheBoxApp.Data.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Mac")
                        .HasColumnType("text");

                    b.Property<int?>("MachineDashBoardPropertiesid")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Os")
                        .HasColumnType("text");

                    b.Property<string>("OsArchitecture")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseExpDate")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseExpStatus")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseKey")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseNotes")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseStatus")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseType")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendor")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorContact")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorEmail")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorNotes")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorPhone")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportExpDate")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportExpStatus")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportNotes")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportStatus")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportType")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendor")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorContact")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorEmail")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorNotes")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorPhone")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorSupport")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorSupportExpDate")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorSupportExpStatus")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorSupportType")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorSupportVendorWebsite")
                        .HasColumnType("text");

                    b.Property<string>("OsLicenseVendorWebsite")
                        .HasColumnType("text");

                    b.Property<string>("OsSerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MachineDashBoardPropertiesid");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("TheBoxApp.Data.Models.MachineDashBoardProperties", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("id"));

                    b.Property<string>("context")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("id");

                    b.ToTable("DashBoardProperties");
                });

            modelBuilder.Entity("TheBoxApp.Data.Models.Machine", b =>
                {
                    b.HasOne("TheBoxApp.Data.Models.MachineDashBoardProperties", "MachineDashBoardProperties")
                        .WithMany()
                        .HasForeignKey("MachineDashBoardPropertiesid");

                    b.Navigation("MachineDashBoardProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
